### PR TITLE
Feature/game piece manager

### LINKED ISSUE #9: Create PlacerDowner Subsystem
Create the subsystem for the manipulator.

### PR DESCRIPTION
**Pull request by Koltara**
Implemented the Picker Upper.

Closes #9

### CODE REVIEW

**Comment by AdamDaMiner** [comment]
Looks all good to me, gramps.

**Review by AdamDaMiner — APPROVED** [review]
Looks all good to me, gramps.

**Review by BigNoah37 — APPROVED** [review]
LGTM :)

**Review by codingwithcn — APPROVED** [review]
Love the naming conventions, they are very.... unique

**Pull request merged**
